### ISSUE TITLE
coretasks: parse RPL_ISUPPORT

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel#1082]
We should parse `RPL_ISUPPORT` to ensure we're doing the right thing with regards to Identifier parsing (`CHANTYPES`), account tracking (`WHOX`/`CASEMAPPING`), channel permission levels (`PREFIX`) and so on.

Documentation on individual params http://www.irc.org/tech_docs/005.html
Rough usage statistics http://stats.ircdocs.horse/isupport/
- [x] network name (`NETWORK`)
- [x] privilege prefixes (`PREFIX`)
- [x] channel prefixes (`CHANTYPES`)
- [x] account tracking (`WHOX`/`CASEMAPPING`)
- [x] multiple NAMES prefixes (`NAMESX`)
- [x] maximum message destinations (`MAXTARGETS`)
  - [x] also target maximums in general (`TARGMAX`)

----

All of this and more is parsed and exposed through #1758 and #1769. – @dgw edit

**Comment by dgw** [comment]
Hijacked the OP with an edit, sorry @maxpowa. :)

**Comment by dgw** [comment]
Done by @Exirel in #1758 (with a little bonus MYINFO stuff in #1769).
