### ISSUE TITLE
Implement all known/relevant IRC formatting codes

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1302]
Sopel is missing (as of 6.5.2) these known IRC formatting options (based on the "[horse docs](https://modern.ircdocs.horse/formatting.html)" living specs):

- [x] italic — e.g. `\x1ditalic` ➜ _italic_ (#1300)
- [x] strikethrough — e.g. `\x1estrikethrough` ➜ ~~strikethrough~~ (#1301)
- [x] monospace — e.g. `\x11monospace` ➜ `monospace` (#1301)
- [x] hex colors — e.g. `\x0499FFCCcolored text` ➜ &lt;can't be done in Github markdown&gt; (#1368)
- [x] reverse color — e.g. `\x16reversed text` ➜ &lt;can't be done in Github markdown&gt; (#1379)
- ~~blink/flash — appears to be `\x06`, but need more research (mentioned in ircdocs/modern-irc#53, might be NAK as it seems unsupported in more modern clients)~~ NAK until/unless a client that actually does something with it can be found

**Comment by dgw** [comment]
More than half of this is already done and I'm working on the rest. Why not just put all of these in 6.6.0?

**Comment by SoniEx2** [comment]
<span style="color: #16aa77">test</span>

**Comment by dgw** [comment]
I'll try to implement the colors this week. Assuming I find the time, I don't expect it to be hard.

**Comment by dgw** [comment]
About to merge the last of these, so this is good to close.
