### ISSUE TITLE
Overhaul setup.py metadata

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1311]
Sopel's `setup.py` could do with some love. Most importantly, it would be beneficial to add project classifiers, and to specify which Python versions the package is compatible with directly in the `setup` function.

This is kind of a tracking issue, so I'll keep the task list here:

- [x] Classify project using appropriate [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers) [#1458]
- [x] Add `python_requires` entry to `setup()` call in `setup.py` [#1522]
- [x] Sort out author/maintainer/contributor/whatever people [#1787]
  - Embolalia is still listed as author, despite stepping down as maintainer, so it would be useful to update that field and add other major contributors for the Sopel 7 release series

**Comment by dgw** [comment]
"Overhaul", to me, implies "for next major release".

**Comment by Exirel** [comment]
We should also have a look at a possible `setup.cfg` file, while we are at it. I leave a note here as a reminder that I should suggest something - if not a PR!

**Comment by Exirel** [comment]
I know right... :(

**Comment by Exirel** [comment]
I added `python_requires` to #1522 and the trove classifiers were added by #1458

**Comment by Exirel** [comment]
So what's left? Authors?

**Comment by dgw** [comment]
Yeah, the authors/maintainers/contributors should be updated at the end of 7.0 dev cycle, right before release. I'll take care of it, don't worry. :)

**Comment by dgw** [comment]
I'm going to call this done. Nitpicks of the final steps will be handled in #1787.

Too bad Python packaging metadata doesn't seem to support the concept of multiple project authors… but that's why we have a CREDITS file.
