### ISSUE TITLE
Remove remaining uses of sopel.web in core

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1316]
All remaining core modules that still use `sopel.web` should be updated to use `requests` directly instead. I'll be doing this in bits of spare time when I don't feel like working on anything substantial.

Modules I found in my search (and migration status):

- [x] bugzilla
- [x] etymology
- [x] isup
- [ ] ~~meetbot (still using `quote`, which should be replaced or refactored)~~ NAK for now, pending #1318
- [ ] ~~reddit (using `sopel.web.USER_AGENT`, which should probably be defined somewhere else)~~ NAK for now, pending #1318
- [x] safety
- [x] search
- [x] tld
- [ ] ~~translate (imports _both_ `requests` and `sopel.web`...because it needs `web.decode()`)~~ NAK for now, pending #1318
- [ ] ~~url (uses `web.decode()` and `web.iri_to_uri()`)~~ NAK for now, pending #1318
- [x] wiktionary (left `web.quote()` in for now)

**Comment by dasu** [comment]
isup: web.get is used, but i'm wondering if we should do requests.head instead.  Would save on downloading the whole site to get an answer the headers would have provided anyways.

PS: etymology doesn't seem to be working

**Comment by dgw** [comment]
web didn't have a head method, so switching is totally on the table.

etymology not working is a separate issue, #1248

**Comment by dgw** [comment]
Closing this, as everything that was planned has been done. Can be reopened and updated if anything happens with #1318 (or a new tracking issue created for the moved functions).
