### ISSUE TITLE
Modernize docstrings & make everything consistent

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1565]
This whole initiative started with #1563, but I only dealt with one file in that PR.

The whole public API (at _least_) should get an overhaul before we release 7.0, to make sure the API docs are really nice and easy to use. We only use Sphinx magic like `:param:` descriptions in a few places so far, and it would be **awesome** to have those everywhere.

Here's the important (public) stuff:

  - [x] `sopel.bot` (#1772)
  - [x] `sopel.cli` (#1922)
    - Probably already modern given that @Exirel wrote it, but ~~I'll still go~~ @Exirel went through it again
    - Review/overhaul pushed to 7.1
  - [x] `sopel.config` (#1778)
    - [x] `sopel.config.core_section` (#1778)
    - [x] `sopel.config.types` (#1719)
  - [x] `sopel.db` (#1776)
  - [x] `sopel.formatting` (#1766)
  - [x] `sopel.irc` (#1772)
    - [x] `sopel.irc.abstract_backends` (#1772)
    - [x] `sopel.irc.backends` (#1772)
    - [x] `sopel.irc.utils` (#1772)
  - [x] `sopel.logger` (#1775)
  - [x] `sopel.module` (#1770)
  - [x] `sopel.tools` (#1563)
    - [x] `sopel.tools.calculation` (#1771)
    - [x] `sopel.tools.jobs` (#1771)
    - [x] `sopel.tools.target` (#1771)
    - [x] `sopel.tools.time` (#1771)
    - [x] `sopel.tools.web` (moved from `sopel.web` in #1616; doc updates in #1669)
  - [x] `sopel.trigger` (#1782)

This stuff is more internal, and it's not as important to get done in time for 7.0, but it would still be great to have nice, consistent docs for at some point:

  - [x] `sopel.coretasks` (#2001)
    - Proper documentation of everything in here would help core development immensely, even if it's not published in the public API docs
  - [x] `sopel.loader` (#2004)
  - [x] `sopel.plugins` (#2002)
    - [x] `sopel.plugins.handlers` (#2002)
    - [x] `sopel.plugins.exceptions` (already done, checked by #2002)
  - [x] `sopel.test_tools` (deprecated, see #2003)

Note that even though I assigned this issue to myself, anyone should feel free to tackle something on this list in a PR. The review process might be tedious (I'm picky about grammar), but it will all be worth it when we release Sopel 7 and bump the website to show the shiny modern API documentation in all its glory! (**Edited to add:** We have a [preview site](https://preview.sopel.chat/) which shows the updated docs, but it's not always quite caught up on the latest `master` changes. We're trying to be nice to our site deployment service by forcing rebuilds somewhat infrequently, since they host us for free.)

**Comment by Exirel** [comment]
I can't stress enough how much I love this. Let's do this!

**Comment by Exirel** [comment]
I think in #1697 I worked a bit on that for `sopel.irc` and `sopel.bot`.

**Comment by dgw** [comment]
Pushing this issue back to 7.1 now that everything I wanted to do for 7.0 is at least PR-ready.

**Comment by Exirel** [comment]
Everything has a PR associated now.

**Comment by dgw** [comment]
All associated PRs are merged now. It's done! 🎊 🚀 🎊
