### ISSUE TITLE
Python2 Deprecation

### ISSUE THREAD

**Issue by half-duplex** [sopel-irc/sopel#1801]
- [x] `setup.py` manual py2 version checks
- [x] `setup.cfg` version restrictions
- [x] `sopel/cli/run.py` py2 version check "sopel 8.0"
- [x] remove unnecessary `__future__`s
- [x] add available `__future__`s
- [x] remove `str = unicode`s
- [x] remove `checkstyle.sh` py3_unicode check
- [x] audit `sys.version_info` uses
- [x] replace `tools.iteritems(x)` uses with `x.items()`
- [x] search for "py2"/"python2" comments

**Comment by smoothstreams** [comment]
Does anyone work anymore ?

**Comment by RhinosF1** [comment]
> Does anyone work anymore ?

On the project or in real life?

Assuming you mean on the project, this will happen when Sopel 8 comes out.

**Comment by smoothstreams** [comment]
> > Does anyone work anymore ?
> 
> On the project or in real life?
> 
> Assuming you mean on the project, this will happen when Sopel 8 comes out.

Yes on the project.  I see, good stuff.  I see like 77 open issues, and its quite sad.  I hate seeing open issues on projects.
I would love to pay someone to just work on this stuff full time.

Also Jan to now, for a release is like 11-12 months.  How big and complicated is this really ?

**Comment by RustyBower** [comment]
Pull requests are open :)

**Comment by Exirel** [comment]
![image](https://user-images.githubusercontent.com/3259552/100486961-ac95df00-3106-11eb-8a4d-84639cf4b8cd.png)

We are working on Sopel 7.1, lots of [the selected issues have a PR opened](https://github.com/sopel-irc/sopel/issues?q=is%3Aopen+is%3Aissue+milestone%3A7.1.0+sort%3Acreated-asc) at different state of approval.

**Comment by dgw** [comment]
In this project, many (probably most) issues represent things we _want_, not things that are _broken_. It's not "sad" to have future plans. Those of us who do work on Sopel mostly do so because it's _fun_ and there's no time pressure. We don't _want_ it to feel like a job.

Not sure why you think there hasn't been a release since January. The last update was [less than two weeks ago](https://pypi.org/project/sopel/7.0.7/). We're working on a smaller feature release that won't change Python version compatibility, and then once that's done someone (really, all of us) will start on removing old Python stuff for the next major version.

**Comment by Exirel** [comment]
Reading this about [future imports](https://docs.python.org/fr/3.6/library/__future__.html) it looks like we'll need only `generator_stop` and nothing else!
