### ISSUE TITLE
tools: command-regexp functions shouldn't be public

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1887]
The major rule-system rework in #1873 is a great excuse to take the `get_*_regexp()` and `get_*_pattern()` functions from `sopel.tools` and either shove them into someplace like `sopel.plugins.rules.utils` or encapsulate the pattern generation into the different rule object classes.

@Exirel let's come back to this after #1873 is finished.

**Full to-deprecate list (for 7.1):**
- [x] `compile_rule()` [#2027]
- [x] `get_command_regexp()` [#1944]
- [x] `get_command_pattern()` [#1944]
- [x] `get_nickname_command_regexp()` [#1944]
- [x] `get_nickname_command_pattern()` [#1944]
- [x] `get_action_command_regexp()` [#1944]
- [x] `get_action_command_pattern()` [#1944]

**Full to-delete list (for 8.0):**
- [x] `compile_rule()` [#2141]
- [x] `get_command_regexp()` [#2141]
- [x] `get_command_pattern()` [#2141]
- [x] `get_nickname_command_regexp()` [#2141]
- [x] `get_nickname_command_pattern()` [#2141]
- [x] `get_action_command_regexp()` [#2141]
- [x] `get_action_command_pattern()` [#2141]

**Comment by dgw** [comment]
Updating the OP based on discussion in https://github.com/sopel-irc/sopel/pull/1944#discussion_r495330811

**Comment by dgw** [comment]
This wasn't supposed to be auto-closed. Whoops.

**Comment by dgw** [comment]
The rest of this is for 8.0; reassigning milestone.
