### ISSUE TITLE
IRCv3 "bot" mode support

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2079]
### Background
Spec: https://ircv3.net/specs/extensions/bot-mode

This extension adds a new ISUPPORT token for servers to advertise a mode that `BOT` clients may set on themselves to indicate their non-human status. Clients with the bot mode enabled are supposed to have their messages tagged with `bot` (well, `draft/bot` until spec ratification) so other clients can act appropriately.

### Plans
I see ~~two~~ _three_ different, but related, things for Sopel to do here:

- [x] Set the bot mode specified in the `BOT` token from ISUPPORT, if given, unless the config explicitly overrides it (can be as simple as looking for the modechar in `core.modes` and skipping this behavior if it's present, [as Limnoria does](https://github.com/ProgVal/Limnoria/blob/711db72ad0224c3f5d094ccd3167a3362a1ce37e/src/irclib.py#L2271-L2272)). [#2088]
- [x] Start ignoring other clients whose messages are tagged as `bot`, so there will be less manual `.blocks add BotNick` work needed from Sopel admins whose instances share channels with other compliant bots and want to minimize the risk of mutual triggers. [#2089]
  - This will also require adding support for the `message-tags` CAP, since the `bot` tag is not sent to clients who have not requested `message-tags`. It shouldn't be much more work than adding it [here](https://github.com/sopel-irc/sopel/blob/269498a8ce29d75cf5235cf21ce3c4a851341154/sopel/coretasks.py#L897-L903), since there's already tag parsing in place for `server-time` and `account-tag` (the specs for which do _not_ depend on `message-tags` being enabled).
- [x] Should probably have a `@plugin.allow_bots` decorator like that allows a callable to receive messages tagged as coming from another bot. [#2244]

**Comment by dgw** [comment]
Oops, yes. Updated the OP, and I guess this is ready to close.
