### ISSUE TITLE
Cleanup/refactoring for 8.0

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2120]
_Originally posted by @half-duplex in https://github.com/sopel-irc/sopel/issues/2062#issuecomment-856886914_

- [x] sopel/formatting.py TODO (#2122)
- [x] conftest.py 2x "Python 3.3" comments (#2123)
- [x] sopel/plugins/rules.py has a 2.7 TODO (#2124)
- ~~[ ] sopel/irc/backends.py SSLAsynchatBackend.handle_connect~~ NAK; replaced by asyncio backend

**Comment by dgw** [comment]
Got PRs for the first three. I'd have to study more about that `SSLAsynchatBackend` one, if it's even worth doing before @Exirel starts on that planned rewrite using `asyncio` instead of `asynchat`.

**Comment by Exirel** [comment]
Not sure it's worth it indeed.

On the other hand, I'm still pondering if using asyncio vs using a threading approach wouldn't be better anyway, since Sopel *does not* take advantage of asyncio in any way (there is no coroutine/async/await, and it won't be possible to use them any time soon).

**Comment by dgw** [comment]
Whether threading or asyncio, it's probably best to refactor Soon™. Looks like the current asyncore/asynchat backend is going to trigger `DeprecationWarning` in Python 3.10: python/cpython#26904

Honestly we should be surprised (and grateful) that it took this long (almost 5 years since 3.6.0 final).

**Comment by Exirel** [comment]
All done from this list.

**Comment by dgw** [comment]
> All done from this list.

Is the backend one "done" by virtue of that class being replaced? 😁

**Comment by Exirel** [comment]
Absolutely. :grin: 
I don't know if there are other items to consider, so I didn't close the issue.

**Comment by dgw** [comment]
Consider? Yes. I found some stuff to triage by searching the whole repo for "todo".

Py2 and cleanup/follow-through categories are the ones I'd consider important to either complete or update comments with a revised plan to handle in 8.1/9. Some of these items may require not-insignificant refactoring, which is why I included "update comments with a revised plan" as an option.

Future planning category would be nice to think about before we cut a new major version, but aren't _required_.

Misc. is obviously the least important. I threw things in there when I didn't necessarily understand what's being asked, or think it'll take under 15 mins to address.

<details>
<summary>Py2-is-dead stuff</summary>

https://github.com/sopel-irc/sopel/blob/b9b827a1c8c6060ad0bb424cc3cd0c194c6a4ea9/sopel/modules/currency.py#L147-L148

https://github.com/sopel-irc/sopel/blob/8b463a0e49cac7a27dc528a180243a6a5183d1f9/sopel/plugins/handlers.py#L61

https://github.com/sopel-irc/sopel/blob/8b463a0e49cac7a27dc528a180243a6a5183d1f9/sopel/plugins/handlers.py#L462

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/tests/mocks.py#L121

</details>

<details>
<summary>Other cleanup/follow-through stuff</summary>

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/plugin.py#L1407-L1408

https://github.com/sopel-irc/sopel/blob/b9b827a1c8c6060ad0bb424cc3cd0c194c6a4ea9/sopel/modules/currency.py#L75-L79

https://github.com/sopel-irc/sopel/blob/b9b827a1c8c6060ad0bb424cc3cd0c194c6a4ea9/sopel/modules/currency.py#L221-L225

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/test/plugins/test_plugins_rules.py#L1921-L1923

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/test/plugins/test_plugins_rules.py#L2239-L2241

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/test/plugins/test_plugins_rules.py#L2444-L2446

</details>

<details>
<summary>Future planning stuff</summary>

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/irc/__init__.py#L103-L107

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/modules/admin.py#L425-L426

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/tools/web.py#L135-L136

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/tools/web.py#L151-L152

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/tools/web.py#L166-L167

https://github.com/sopel-irc/sopel/blob/5c4f56e505442031bea4affaa00cae722b61111d/sopel/tools/web.py#L200-L202

</details>

<details>
<summary>Misc., idk-might-be-easy stuff</summary>

https://github.com/sopel-irc/sopel/blob/b9b827a1c8c6060ad0bb424cc3cd0c194c6a4ea9/sopel/tests/pytest_plugin.py#L90

https://github.com/sopel-irc/sopel/blob/b9b827a1c8c6060ad0bb424cc3cd0c194c6a4ea9/sopel/modules/tell.py#L68-L69

</details>

**Comment by dgw** [comment]
AFAIK this is actually done. If we missed anything, it'll get caught Eventually™ as we continue rewriting and extending stuff.
