### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by elad661** [sopel-irc/sopel#236]
We should attempt to support Python3 while keeping support for Python 2.x

Things we could use:
- `from __future__` imports
- [2to3](http://docs.python.org/2/library/2to3.html)
- conditional importing of files: create a tools3.py file that will have stdout and stderr with Python 3 syntax. Conditionally load it instead of tools.py in case we are running on Python 3.

Issues we should figure out and things we should do:
- [x] `from __future__ import print_function` in all modules that uses `print` directly
- [x] `from __future__ import unicode_literals` and `#encoding=utf8` in all files
- [x] Python3 strings causes strange Asyncore errors (type string doesn't support the buffer API)
- [x] Research supporting both 2.x and 3.x with the same codebase
- [x] Figure out the best way to do conditional loading without duplicating too much code
- [ ] Check which external dependencies have Python 3 ports and try to find a way to use them without duplicating module code
