### ISSUE TITLE
systemd support

### ISSUE THREAD

**Issue by elad661** [sopel-irc/sopel#262]
- [x] Service file
- [x] Service file with multiple instances support (#1059)
- [ ] systemd Journal integration for logging
- [x] Fedora spec file changes to accommodate new features
- [x] Issue #261

**Comment by anarcat** [comment]
relevant: https://github.com/sopel-irc/sopel/pull/1059

**Comment by dgw** [comment]
Reopening to look at completing this task list in 7.0.0.

**Comment by Exirel** [comment]
I think most of the work has been done, at least from what I know of systemd on Ubuntu.

However, the user-experience is not really optimal, as you have to configure yourself the file, or know the exact location of the config file, etc.

More documentation, or better tooling could be interesting in this case.

**Comment by dgw** [comment]
According to [the systemd-journald service documentation](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Stream%20logging):

> The systemd service manager invokes all service processes with standard output and standard error connected to the journal by default. This behaviour may be altered via the `StandardOutput=`/`StandardError=` unit file settings, see [systemd.exec(5)](https://www.freedesktop.org/software/systemd/man/systemd.exec.html) for details. The journal converts the log byte stream received this way into individual log records, splitting the stream at newline ("\n", ASCII `10`) and `NUL` bytes.

Our last remaining checkbox (supporting systemd Journal integration for logging) might already be done, then, and we can maybe close this issue. Our example systemd unit files don't override that default.

I'm running Sopel in production on an old Upstart system, personally, so someone else should check my research. @ddstreet, you just opened a systemd-related PR earlier today. Would you mind weighing in?

**Comment by dgw** [comment]
I'd argue that journal support is pretty irrelevant now with the improvements to Sopel's own logging (see #1678). Let's just close this one.

**Comment by Exirel** [comment]
I think it's actually "done".

**Comment by ddstreet** [comment]
> I'm running Sopel in production on an old Upstart system, personally, so someone else should check my research. @ddstreet, you just opened a systemd-related PR earlier today. Would you mind weighing in?

really sorry, for some reason I just got an email for this with the last comment, and I missed your comment from March.

in any case, seems like this is all done, but sorry for missing your earlier request.
