### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#268]
The test program should do the following steps
- [ ] Run Willie.
- [x] Execute core tests.
- [ ] Detect loaded modules.
- [ ] Find tests for loaded module and execute these.
- [ ] Generate human-readable test report to file. (Currently to stout)

**Comment by maxpowa** [comment]
There's some pretty decent core coverage (triggers/module/basic connection) at this point. I think having visibility to coverage on commits would help increase the push for testing. Can we allow Travis access to the org so we can run tests on commits?

**Comment by Exirel** [comment]
The Travis CI works fine so far! Sure thing the coverage is not the best yet, but it's improving - at least I'm working on it, slowly, but surely.

I don't know if we need an issue to follow the progress, or maybe a new issue to list the critical parts that require testing - or code refactoring to ease testing.

**Comment by dgw** [comment]
This is one of those issues so old I didn't get back far enough in the history when I took over the project last year and went around labeling/triaging stuff.

With multiple CI services checking every push to `master` and every opened pull request, I don't think we need this issue open any more. Sopel _has_ tests. They might not cover everything, but they do exist.

@Exirel Since you're already involved in the testing initiative, I'll ask you: Should we continue amending this issue to track what still needs testing/refactoring, or use a new one? Your opinion is important to me in this case, because I think you'll end up doing a lot of the relevant work. :smile_cat:

**Comment by Exirel** [comment]
@dgw as you said, multiple services are now in use to run tests and check quality of code - so for me the issue is fixed, and all the project need is to write test.

So let's close this one and we'll see later what we need. 👍
